### ISSUE TITLE
tint on BitmapText doesn't update when supplied in style

### ISSUE THREAD

**Issue by getkey** [michalochman/react-pixi-fiber#183]
### Description

```ts
<BitmapText
	font="35 Press Start 2P"
	tint={color}
/>
```
This works perfectly, the tint updates as expected.

But this doesn't. It's set to the color that was specified when it was created, but even when the color change, it doesn't update. I haven't tried the other parameters `font.name` and `font.size` but they might have the issue too.

```ts
<BitmapText
	style={{
		font: {
			name: 'Press Start 2P',
			size: 35,
		},
		tint: color,
	}}
/>
```

### Steps to reproduce

It's a bit of a pain to create a reduced test case for BitmapText since it needs to download stuff etc. so I hope you'll forgive me for linking to my repo instead.

1. clone https://github.com/getkey/ble/
2. checkout commit 18fa505207aca80bf97f1bb339c07461e4d522cf
3. `yarn dev`
4. this is the component that's supposed to change colors when you click on it https://github.com/getkey/ble/blob/18fa505207aca80bf97f1bb339c07461e4d522cf/src/components/Text.tsx#L19

### Additional info

- react-pixi-fiber version: 0.14.0
- React version: 16.13.1
- ReactDOM version: 16.13.1
- PixiJS version: 5.2.3

**Comment by michalochman** [comment]
Hi @getkey, thanks for reporting. This is not intuitive behavior, but it is actually to be expected – `style` is only used during initialization of `PIXI.BitmapText` (as constructor argument) and is not available as a property of `BitmapText` later. Because of this, it is not something that can be fixed without implementing custom updates for different components.

Your workaround is the solution that should be used for setting and changing `BitmapText` tint.

**Comment by getkey** [comment]
I see! Thanks, closing this issue then. :slightly_smiling_face:

**Comment by getkey** [comment]
`font` has been deprecated, so the workaround no longer works.

**Comment by michalochman** [comment]
Hi @getkey, `font` has been deprecated but you can still set tint using `tint` property, just extract it from `style` you are using. Is this workaround enough for you?

From the perspective of `BitmapText` component, the `style` property should probably not be used in react, because it is not how the updates are done by PixiJS – style is used only in `BitmapText` constructor, if you want to update the instance later, you need to use `fontName`, `fontSize`, `align`, `tint`, `maxWidth` and `letterSpacing` setters, and those are the props you should be using if you intend to change them.

**Comment by getkey** [comment]
Oh great! I overlooked the new setters. Thanks, closing!

**Comment by michalochman** [comment]
Yes, I noticed that.

Ideally `style` prop for `BitmapText` is handled in a special way by `react-pixi-fiber` or at least `style`/`style.fontName` is automatically generated from other props, I'll add this as an improvement issue.
