### ISSUE TITLE
Cannot work in React 17 with `createStageClass`

### ISSUE THREAD

**Issue by huang-yuwei** [michalochman/react-pixi-fiber#201]
### Description
`Cannot read property 'alternate' of undefined` shows when using `createStageClass ` to create a Stage.
To solve the https://github.com/michalochman/react-pixi-fiber/issues/164 issue, I use `createStageClass ` in my App, but it doesn't work after upgrading React to 17x. If I don't use `createStageClass `, it seems to work fine, but then https://github.com/michalochman/react-pixi-fiber/issues/164 issue will happen again.

### Steps to reproduce
https://codesandbox.io/s/alternate-error-in-react-pixi-fiber-with-react17-gkc3o?file=/src/App.js

### Additional info

- react-pixi-fiber version: 0.14.2
- React version: ^17.0.0
- ReactDOM version: ^17.0.0
- PixiJS version: 5.3.3

**Comment by michalochman** [comment]
Thanks for the report @huang-yuwei – I'll check this.

**Comment by michalochman** [comment]
Turns out we can't support both React 16 and React 17 due to changes to `react-reconciler` API changes. I'll have to think how to approach this: either drop support for React 16 or build 2 separate packages.

@huang-yuwei is there a specific reason you need to use `Stage` as class?

**Comment by huang-yuwei** [comment]
@michalochman 
Thank you for the quick investigation. 
The reason why I am using `Stage` as a class is for solving the rendering issue in Safari, which is as same as the issue in #164. Otherwise, I prefer using an imported `Stage` as well.

**Comment by michalochman** [comment]
Aha, interesting. Can you try `react-pixi-fiber@1.0.0-beta.5`? The other issue you are mentioning was not reproduced in `1.0.0` branch.

Don't fear the `beta` tag, it's stable. I was only not able to release it for the public because I didn't have time to document upgrade instructions as some internal stuff in `react-pixi-fiber` and they were used in some projects that I know about.

**Comment by huang-yuwei** [comment]
Ooh, didn't know `1.0.0-beta.5` is a stable version. I thought it is still unstable so I didn't use it on my project.
It seems like it works like a charm. Thank you for your support.

Although I found another error, and I haven't investigated the reason.
After upload to React 17.x (not matter react-pixi-fiber is 1.0.0-beta.5 or 0.14.2), an error shows if I assign `parentGroup `(feature from `pixi-layers`) to `Container`.

Error detail: VM1274:37 Warning: React does not recognize prop `parentGroup` on `<Container />`. If you accidentally passed it from a parent component, remove it from `<Container />`.

**Comment by michalochman** [comment]
This is a warning shown in development mode, not an error, and it comes from `react-pixi-fiber@1.0.0` version.

I have implemented it to show props that users may have misspelled or used incorrect type. When it was initially implemented, `react-dom` was showing similar warning, then it got removed from `react-dom` (you can use arbitrary props now on HTML element component), so I will either remove this feature or make it optional in development, probably the former as it increases build size.

Feel free to ignore it. It is shown, because the `parentGroup` is not recognised prop of `Container`, as it comes from plugin.

**Comment by huang-yuwei** [comment]
> Don't close it, I will close it when I decide how to resolve React 16/17 support.

👌

> it comes from react-pixi-fiber@1.0.0 version.

Sorry that I misreading the version 

> Feel free to ignore it. It is shown, because the parentGroup is not recognised prop of Container, as it comes from plugin.

It is a little bit hard to ignore it during development 😇 
Before you made the decision of removing it or making it optional, I probably may not upgrade to `1.0.0-beta.5`

---

Thank you for making this amazing dependency 🙌
It helps a lot, and giving me and my team a power tool to make something possible

**Comment by michalochman** [comment]
@huang-yuwei I have just published `react-pixi-fiber@1.0.0-beta.6`. The prop type validation mentioned is now only working if you use `<React.StrictMode />`. Additionally, it is possible to mark custom properties as "known", I forgot this was implemented already.

I have added relevant examples:
1. Enable prop type validation in `<React.StrictMode />`: https://github.com/michalochman/react-pixi-fiber/blob/87438bed93bf1c3dd5cd149d6cda9a2984a823ae/examples/src/CustomPIXIPropertyExample/index.js#L21-L26
2. Mark custom property as known: https://github.com/michalochman/react-pixi-fiber/blob/87438bed93bf1c3dd5cd149d6cda9a2984a823ae/examples/src/CustomPIXIPropertyExample/index.js#L11

**Comment by huang-yuwei** [comment]
@michalochman 
Thank you again for the amazingly fast support.
I have tied the `1.0.0-beta.6` in my project, and it works without any additional warnings. 
Besides, the `React. StrictMode ` and `CustomPIXIProperty ` are helpful as well 🙌

**Comment by michalochman** [comment]
`react-pixi-fiber@1.0.0` released.
