### ISSUE TITLE
Stage would not render correctly when resizing window 

### ISSUE THREAD

**Issue by myktsk** [michalochman/react-pixi-fiber#204]
### Description
The `Stage` with hook would not render correctly(details below) on resizing the window if the continuous ticker is stopped (`ticker.stop()`)  and  `render` manually triggered. We would want to stop the ticker because of performance concerns (i.e. We don't want our app to constantly keep rendering if there is no change in the state of the app). 
Switching to a class-based stage with `createStageClass` would solve the issue, but I thought it'd be great if we could use the function-based `Stage` with the same behavior.

- Chrome(v89.0.4389.72) and Safari(v14.0.3): 
The content inside the `Stage` would look spread/shrunken when the window is resized in certain ways (like opening and closing chrome developer tools, resizing the window when a different tab is opened, and come back to the app) 
  Normal: 
  <img width="200" alt="スクリーンショット 2021-03-05 18 27 34" src="https://user-images.githubusercontent.com/22167483/110095708-886e2c00-7de0-11eb-86bb-59be10bd3e72.png">
  Shrunken:
  <img width="200" alt="スクリーンショット 2021-03-05 18 27 17" src="https://user-images.githubusercontent.com/22167483/110095714-8a37ef80-7de0-11eb-9d0b-44d69dbb29f9.png">
  Spread: 
  <img width="200" alt="スクリーンショット 2021-03-05 18 27 06" src="https://user-images.githubusercontent.com/22167483/110095718-8ad08600-7de0-11eb-8665-756ec292095c.png">

- Firefox(v86.0 ): 
Resizing the window causes the entire `Stage` to blackout occasionally 

### Steps to reproduce
https://codesandbox.io/s/resizable-stage-demo-8dg7q

### Additional info

- react-pixi-fiber version: 1.0.0-beta.7
- React version: 17.0.1
- ReactDOM version: 17.0.1
- PixiJS version: 5.3.7

**Comment by michalochman** [comment]
@myktsk it looks like when using function Stage, your `App` component has `componentDidUpdate` called before the `Stage` gets updated, so essentially you call `app.render` before Stage had  chance to call `resize` on the renderer:

<img width="590" alt="Screenshot 2021-03-05 at 17 38 31" src="https://user-images.githubusercontent.com/1628450/110145851-27dbf080-7dda-11eb-92b6-a515c651e562.png">

When using function Stage it is reverted so it works correctly. I haven't tested manual rendering and resizing so not sure yet why this is happening, but at least we now know what the underlying issue is.

I have checked and seems that there is a workaround to fix this by using `setTimeout` with 0 delay instead of `requestAnimationFrame` to call `app.render`.

I'll leave this issue open for now.

**Comment by myktsk** [comment]
@michalochman Thank you for your quick reply and thorough explanation!
`setTimeout` indeed fixed the resizing issue with Chrome and Safari, but the issue with Firefox seems to remain...
I will stick with the class-based Stage for now as that works completely fine with our app.
But it would be great if you could take a look at it at some point. :)

**Comment by michalochman** [comment]
Fixed in `react-pixi-fiber@1.0.0-beta.8`.
