### ISSUE TITLE
Webpack complains about missing exports in pixi.js

### ISSUE THREAD

**Issue by joukosaastamoinen** [michalochman/react-pixi-fiber#279]
### Description

A bunch of errors about missing exports in `pixi.js` occur when attempting to compile an app that uses the latest versions of `pixi.js` and `react-pixi-fiber`:

```
ERROR in ./node_modules/react-pixi-fiber/es/react-pixi-fiber.development.js 20819:23-45
export 'extras' (imported as 'PIXI') was not found in 'pixi.js'
```

### Steps to reproduce

1. Import and render a `<Stage>` from `react-pixi-fiber`
2. Compile and run the app

### Additional info

- react-pixi-fiber version: 1.0.1
- React version: 18.2.0
- ReactDOM version: 18.2.0
- PixiJS version: 6.5.1

Example app: https://github.com/joukosaastamoinen/react-pixi-fiber-template

To reproduce using the example app, do:

```
npm install
npm start
```

**Comment by joukosaastamoinen** [comment]
I managed to make the error go away by ejecting my test app (which was created using `create-react-app`) and setting the `strictExportPresence` Webpack option to `false`.

**Comment by michalochman** [comment]
Hi @joukosaastamoinen, this is because the build tool is overly cautious. The code being executed is put inside `try...catch` block so the code itself will not break, but we need to use this export to support PixiJS version 4.

As a workaround you can also import CJS build instead of ES build to fix that without, the this comment https://github.com/michalochman/react-pixi-fiber/issues/247#issuecomment-1027893254.

We have plans to address this differently in future version of this library, so I will close this issue.

**Comment by joukosaastamoinen** [comment]
@michalochman Ah ok, makes sense. Thank you for the explanation and workaround!
