### ISSUE TITLE
refs on primitives (animation with react-spring)

### ISSUE THREAD

**Issue by drcmda** [michalochman/react-pixi-fiber#78]
Is there a way to obtain a ref on objects?

I would like to create a native react-pixi target for react-spring, then you could use it to "natively" animate things outside of react. For instance here's an example for react-konva:

using hooks: https://codesandbox.io/s/71xj546m46
using render props: https://codesandbox.io/s/4z2vx0l86x

And this was react-blessed: https://twitter.com/0xca0a/status/1000513216672403456

All i need to enable this is a ref and something to update properties. For instance, here's the kova implementation: https://github.com/drcmda/react-spring/blob/master/src/targets/konva/index.js#L14-L21

Unfortunately ref={r => console.log(r)} returns currently `null`, i could still just animate elements with rendering them 60fps with new props, but that is extremely expensive.

**Comment by michalochman** [comment]
@drcmda it is most certainly possible, it's how I work with most of my animations. Can you provide a sandbox where it returns `null`?

**Comment by michalochman** [comment]
You can find working example in the examples folder if you want, using a ref on ParticleContainer which is a primitive: https://github.com/michalochman/react-pixi-fiber/blob/41c341d8c8a851e9cf3678258b075ac9cb47bf17/examples/src/CustomBunnymarkExample/CustomBunnymark.js#L122

There's also an example of spring animation using animated: https://github.com/michalochman/react-pixi-fiber/blob/41c341d8c8a851e9cf3678258b075ac9cb47bf17/examples/src/AnimatedExample/index.js#L20

**Comment by drcmda** [comment]
I was testing with the first demo on the frontpage (https://codesandbox.io/s/q913r72jo4)

and i'm going

```jsx
function Bunny(props) {
  return (
    <Sprite
      ref={r => console.log(r)}
```

**Comment by michalochman** [comment]
@drcmda the way you're getting ref in this example is by creating new function on each render (with arrow style). Because of that the previous ref callback is called with `null` first and only then the underlying instance is used to call the callback again, see [comment on react issue](https://github.com/facebook/react/issues/4533#issuecomment-261251426) by @gaearon. Should you just used `ref={console.log}` it would log `null` only once, during the first render when it doesn't have the instance yet.

If it's of any help to you, the way I was approaching this problem when I wanted to have ref callback created every time, was doing something like: `ref={r => r !== null && console.log(r)}`.

----

Regarding the `AnimatedSprite` example, you are right that the animated instance will use `forceUpdate` to render animation. However, this is just an example to show that it's possible to integrate animated into react-pixi-fiber and `setNativeProps` was not implemented as a part of this project. I planned to implement native animated target as a part of different library though, but that was never pressing.

**Comment by drcmda** [comment]
in react-spring it would only be a couple if lines, it is in theory driven by animated, though it's faster and easier to use. I'll run some tests and if i have something i'll post here. Thanks for clearing it up, it was indeed the loop - stupid of me to not thinking of that. 😓

**Comment by drcmda** [comment]
PS. is there anything like a set method on the instance or are the various props that i see on the ref reactive already?

**Comment by drcmda** [comment]
Seems to work, thanks for the help! https://codesandbox.io/embed/0qkll4y5nw 🙂 This is animating 60fps, no React/forceUpdate involved. Would be ready for react hooks as well. 

I only needed this for an article explaining on how to write custom targets on the react-spring site. But if you like we could make this into a real target. All it needs is a better understanding on what objects to set.

**Comment by michalochman** [comment]
Glad it worked @drcmda, that's one cool looking demo!

I'm definitely into getting a real target, this might be useful for many users. Let me know what you need to know and we can sort this out. I think I might even resume work on raw animated integration (by implementing `setNativeProps`).

**Comment by michalochman** [comment]
#95 shows an example how to implement Animated that will skip React's `forceUpdate`.
