### ISSUE TITLE
events on stage

### ISSUE THREAD

**Issue by liajoy** [michalochman/react-pixi-fiber#85]
Hi!
Seems there's no way to add events to stage.
Since `DEFAULT_PROPS` and stage `propTypes` doesn't include events key, events is filtered and passed to canvas props.
can I just use stage like other pixi container do?
`
<Stage pointerdown={handler}>
`

**Comment by michalochman** [comment]
Hey @liajoy, thanks for raising the issue. 

A question though before merging #86, any particular reason you want to use Pixi events on `<Stage />` instead of DOM events on `canvas` returned from Stage `render`? The simplest workaround is to add a single `<Container />` to Stage and bind events there.

**Comment by liajoy** [comment]
Pixi event is different with dom event, it provide more infomation and features. For example, event on stage like `pointermove` actually is bind on body, so it can trigger even out of canvas, maybe someone need this.
Add `<Container />` will help, but if `<Stage />` is more similar to Pixi stage,  I can migrate from pixi codes to react codes more easily?

**Comment by michalochman** [comment]
Fair enough. I'll have a look at #86.

**Comment by michalochman** [comment]
@liajoy released as `react-pixi-fiber@0.6.2`, thanks!
