### ISSUE TITLE
batchedUpdates without ReactDOM

### ISSUE THREAD

**Issue by liajoy** [michalochman/react-pixi-fiber#88]
### Description
HI!
`ReactDOM` has a `unstable_batchedUpdates` API to batch `setState` out of React context.
In `react-pixi-fiber`, if the React Pixi Fiber renderer is exported, I can get the `batchedUpdates` from it's instance, But seems it's not.( I think React Pixi Fiber renderer should be the internal. 
So can expose the `batchedUpdates` API? But it's a unstable API, maybe someday it'll be implemented and removed.
Any advise to do this?

**Comment by michalochman** [comment]
Hi @liajoy, in `ReactDOM` it's available because it explicitly exposes `batchedUpdates` from `ReactFiberScheduler` as `unstable_batchedUpdates`. We could also expose it this way if we wanted, that should be easy, you can try it yourself and submit a PR if you want. However, you are right it is unstable. There's a `TODO: Batching should be implemented at the renderer level, not inside the reconciler.` so it will be removed eventually.

**Comment by liajoy** [comment]
Sure! Please take a look.
